### ISSUE TITLE
Highlighting active page/app link in a menu

### ISSUE THREAD

**Issue by mmnosek** [StarcounterFreezer/Launcher#244]
As we are developing more and more complex apps it would be nice to have a possibility to highlight a links in a menu to make the whole navigation more clear. It is a common practice in many kinds of applications. Adding css for `active` links is not the solution, because clicking on menu elements is obviously not the only way to changing active pages.
Most of page changes/redirections are done by setting `MorphUri` attribute. Then link is not set as active from the browser point of view.

I think that this feature should be provided by launcher/some custom element and should be based on a current browser uri. Good navigation is strictly connected with a url's, so it sounds as a proper approach. Maybe listening for a window `onHashChange` event and trying to find out which element should be considered as active? Any ideas?

cc @tomalec @warpech @miyconst

**Comment by tomalec** [comment]
That's the problem that we were struggling for quite long.

I really like the idea of a custom element listening to `window.location`
changes. I would think of  `launcher-menu`.

**Comment by warpech** [comment]
Adding @mattiasmak to create a subscription

**Comment by tomalec** [comment]
I got a feeling that blending with context + Shadow DOM Compositions + surfaces + `display: contents` should give us sufficient tools to solve the use cases I imagine. 

However, we do not have any convention to create menus (like for settings). Do you think we need one?

Do we have any specific client case?

**Comment by warpech** [comment]
Yes, I agree this solution still has to be solved. The biggest question that prevails is how the menu is maintained. Only then we can discuss such details like how the current menu item is highlighted. 

For now, let's move the discussion to the umbrella topic: https://github.com/Starcounter/RebelsLounge/issues/53
