### ISSUE TITLE
Allow Admins to change page title in settings

### ISSUE THREAD

**Issue by mmnosek** [StarcounterFreezer/Launcher#245]
Currently page title is fixed in Launcher HTML and it is always just "Launcher". It doesn't look like something production-ready from the enduser point of view. As our Launcher should be a basis to create complex systems out of the Prefabs and other vendor's apps, I think that it is necessary to allow administrators of apps running together with Launcher to change it's title.

My proposal is exactly to allow editing content of "title" html tag in Launcher from a settings page. The first real world example where I've faced this problem is SWE project. I'm more than sure that in the future there will be more :)

cc @warpech

**Comment by mmnosek** [comment]
@warpech am I right that `DisplayAppTitle` does not solve this problem at all? Do you think it should be used to solve this one as well? Managing solution title should be the high priority for us.

**Comment by warpech** [comment]
`DisplayAppTitle` only shows the title in HTML at the moment. It does not set the window title.

I agree this should be fixed.

I have created an issue with a proposed solution: https://github.com/Starcounter/Website/issues/301. Please comment there.
