### ISSUE TITLE
Make favicon editable/uploadable

### ISSUE THREAD

**Issue by mmnosek** [StarcounterFreezer/Launcher#252]
Currently favicon is fixed in Launcher. IMO it should be anseparate option to upload some favicon file (most likely stored in database). New option should be placed in Launcher's settings page.

cc @warpech

**Comment by mmnosek** [comment]
@warpech should it be moved to the WebsiteEditor? If not, where?

**Comment by warpech** [comment]
I agree this would be a welcome feature. I have created an issue for it, please comment there: https://github.com/Starcounter/Website/issues/302
