### ISSUE TITLE
Make tab/title more meaningful?

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterFreezer/Launcher#262]
Forgive me if this is a bad suggestion, or is just... well, stupid. But would it be possible to make something more out of the title that is shown in the tab when the launcher is running? ATM, it always just say "Launcher".

For example, browsing around in http://inside.starcounter.com/, I would like to see the name of the app I'm currently in, or if I'm at the index page, something "Inside Starcounter".

Ideally, it would even work more like GMail, where the context of where I'm currently at is always shown.

cc @warpech @tomalec

**Comment by warpech** [comment]
Of course it is a good suggestion and there are many ways to do it. But so far we have not worked out a good one. I guess we would love the title to be not only settable but also decoratable by Launcher.

By decoratable I mean that if the system name is "Inside Starcounter" and the current main partial title is "Per Samuelsson - Edit person details", the system integrator might want to display `Per Samuelsson - Edit person details - Inside Starcounter` as the window title.

Simplest way to do it is to create a custom element `<set-tile>` that sets `document.title`. The biggest drawback is that Launcher will not be ready to decorate the content. Another drawback is that multiple micro-partials might be fighting for the window title and sometimes not the "main" partial will win.

I think that a better solution would be to set the window title from `starcounter-composition`, perhaps even using `<set-title>`.

@tomalec any more thoughts?

Related: #245

**Comment by per-samuelsson** [comment]
> By decoratable I mean that if the system name is "Inside Starcounter" and the current main partial title is "Per Samuelsson - Edit person details", the system integrator might want to display `Per Samuelsson - Edit person details - Inside Starcounter` as the window title.

I think thats kind what I meant with

> Ideally, it would even work more like GMail, where the context of where I'm currently at is always shown.

But I'm not as skilled as you explaining stuff in this crazy web domain world. 😄

**Comment by mmnosek** [comment]
Closing this as we have two duplicates, one in the place relevant for `inside.starcounter.com`:
* https://github.com/Starcounter/inside.starcounter.com/issues/41
* https://github.com/StarcounterFreezer/Launcher/issues/245

**Comment by mmnosek** [comment]
Ups, I don't have permissions to close. @warpech could you?
