### ISSUE TITLE
Question: Do you have in your roadmap to make launcher page loading nicer?

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterFreezer/Launcher#289]
### Steps to reproduce
Simply go to https://53.adfenix.com/launcher

### Expected result
A page loader like [this](https://www.webcomponents.org/element/PolymerElements/paper-spinner/demo/demo/index.html) should appear, till the page is loaded with complete View-Model Data.

### Actual result
The page loads in steps : 
![image](https://cloud.githubusercontent.com/assets/4388707/25251624/552a6312-261a-11e7-9844-33776e3b5167.png)
![image](https://cloud.githubusercontent.com/assets/4388707/25251636/59fff5fa-261a-11e7-82fc-01f3fddd95af.png)
![image](https://cloud.githubusercontent.com/assets/4388707/25251639/5d8883ea-261a-11e7-9c59-d620e1749717.png)

##### Starcounter version 
2.3.0.6303

**Comment by miyconst** [comment]
@atifwaqar sorry for so late delay, but Launcher app is deprecated and won't receive any updates.

**Comment by atifwaqar** [comment]
@miyconst But the behavior I explained above is not only with Launcher. It applies to all SC apps. Like for instance Website/People/Signin app has the same behavior as described above.

**Comment by miyconst** [comment]
We are working on improving the page loading experience, the loading icon might be one of the options.
